services:
  codrr_db:
    image: mysql:5.7
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    ports:
      - "3307:3306"
    environment : 
      MYSQL_DATABASE : codrr_db
      MYSQL_ROOT_USER : ucodrr
      MYSQL_ROOT_PASSWORD : secret
      MYSQL_PASSWORD : secret  